spring.application.name=demo

##MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tododb?Timezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=amrkahla6
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=44b63de78d337debbeb33c4b92b1c0a0f376b419b1d8c0e1368794da62de1baf
spring.jwt.expiration=900000
